### PR TITLE
Fix private note marker [Enhancement] Skip note metadata to check for…

### PR DESCRIPTION
**Pull request by aurepereira**
Fix private note marker detection, issue #20
- Select marker in note content
- Select marker in properties

### CODE REVIEW

**Comment by jillalberts** [comment]
Thanks for the PRs. I should have time to take a look at them later today.

**Comment by aurepereira** [comment]
> Thanks for the PRs. I should have time to take a look at them later today.

No worries at all. Regarding this specific PR, I've had a better, easier-to-understand idea on how to proceed so if you could give it a couple days extra that'd be neat. Thanks!

**Comment by aurepereira** [comment]
@jillalberts this PR is ready to be reviewed. I also took the opportunity to fix a bug where callouts would stay in a blurred state no matter the mode. Thank you for your time!

**Comment by jillalberts** [comment]
Thanks! Published as version 0.7.4 !

**Pull request merged**
